name: Node.js CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:  
  USERNAME: ${{secrets.DOCKER_USERNAME}}
  PASSWORD: ${{secrets.DOCKER_PASSWORD}}
jobs:
  build:
    name: Build Node.js Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t anuragsingh2207/hello-world-node:latest .

      - name: Docker Login
        run: docker login -u="${{env.USERNAME}}" -p="${{env.PASSWORD}}"

      - name: Push Docker Image
        run: docker push  anuragsingh2207/hello-world-node:latest .
