name: Node.js CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    name: Build Node.js 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Build Docker Images
        run: docker build -t hello-world-node:latest .
